name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./Notification/pom.xml
          mvn clean package -f ./App/pom.xml
          mvn clean package -f ./Calculate/pom.xml
          mvn clean package -f ./Remittance/pom.xml

      - name: Docker Build and push for Notification
        uses: docker/build-push-action@v4
        with:
          context: ./Notification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notification:latest
            ghcr.io/${{ github.repository }}/notification:${{ github.ref_name }}
            
      - name: Docker Build and push for App
        uses: docker/build-push-action@v4
        with:
          context: ./App
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/app:latest
            ghcr.io/${{ github.repository }}/app:${{ github.ref_name }}
            
      - name: Docker Build and push for Calculate
        uses: docker/build-push-action@v4
        with:
          context: ./Calculate
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/calculate:latest
            ghcr.io/${{ github.repository }}/calculate:${{ github.ref_name }}
            
      - name: Docker Build and push for Remittance
        uses: docker/build-push-action@v4
        with:
          context: ./Remittance
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/remittance:latest
            ghcr.io/${{ github.repository }}/remittance:${{ github.ref_name }}
            
